Vat overhaul
GEWIS/parelpracht-server pull request #17
Opened 2022-11-10 13:09 UTC by Gijsdeman

2022-11-10 13:10 UTC, Gijsdeman commented
Er zitten nog wat dingen in (voornamelijk mbt custom invoices) die wat netter kunnen, maar die los ik later wel een keer op. Backend veranderingen zijn [hier](https://github.com/GEWIS/parelpracht-client/pull/31) te zien.

2022-11-15 15:00 UTC, Yoronex requested changes

2022-11-15 15:00 UTC, Yoronex commented on src/controllers/VATController.ts
> +export class VATController extends Controller {
Even in de readme toevoegen dat je handmatig (in de database) VAT entities moet maken. Er is namelijk geen POST endpoint.

2022-11-15 15:00 UTC, Yoronex commented on src/pdfgenerator/parameters.json
> +}
Dit bestand mag weg

2022-11-15 15:00 UTC, Yoronex commented on tsconfig.json
> +    "src/pdfgenerator/parameters.json",
Deze mag weg als je de .json verwijdert

2022-11-21 10:59 UTC, Gijsdeman commented
Everything resolved, pls merge

2022-12-20 17:27 UTC, Yoronex approved these changes

2022-12-20 17:27 UTC, merged